# Generated by Django 5.2.3 on 2025-08-08 10:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.IntegerField()),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], max_length=20)),
                ('type', models.CharField(choices=[('SPELL', 'Spell'), ('UNIT', 'Unit'), ('EQUIPMENT', 'Equipment'), ('ASSET', 'Asset'), ('EVENT', 'Event'), ('TRAP', 'Trap'), ('RITUAL', 'Ritual'), ('OTHER', 'Other')], max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('is_character_card', models.BooleanField(default=False)),
                ('is_character_exclusive', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True)),
                ('classlock', models.CharField(choices=[('SPECIALIST', 'Specialist'), ('SPELLWEAVER', 'Spellweaver'), ('BLOODBOUND', 'Bloodbound'), ('SHADE', 'Shade'), ('MACHINIST', 'Machinist'), ('SOULFORGED', 'Soulforged'), ('GAMBLER', 'Gambler'), ('OATHBOUND', 'Oathbound'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('auxiliarytype', models.CharField(choices=[('NONE', 'None'), ('REAGENT', 'Reagent'), ('OATH', 'Oath'), ('CONSUMABLE', 'Consumable'), ('FRAGMENT', 'Fragment'), ('RELIC', 'Relic')], default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('height_cm', models.FloatField(default=0.0)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONBINARY', 'Nonbinary'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('birth_date', models.CharField(blank=True, max_length=20)),
                ('short_bio', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('model_file_path', models.CharField(blank=True, max_length=255)),
                ('class_type', models.CharField(choices=[('SPECIALIST', 'Specialist'), ('SPELLWEAVER', 'Spellweaver'), ('BLOODBOUND', 'Bloodbound'), ('SHADE', 'Shade'), ('MACHINIST', 'Machinist'), ('SOULFORGED', 'Soulforged'), ('GAMBLER', 'Gambler'), ('OATHBOUND', 'Oathbound'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('health', models.IntegerField(default=0)),
                ('passive_ability_ref', models.CharField(blank=True, max_length=100)),
                ('passive_description', models.TextField(blank=True)),
                ('active_ability_ref', models.CharField(blank=True, max_length=100)),
                ('active_description', models.TextField(blank=True)),
                ('partner_ability_ref', models.CharField(blank=True, max_length=100)),
                ('partner_description', models.TextField(blank=True)),
                ('solo_bonus_ref', models.CharField(blank=True, max_length=100)),
                ('solo_bonus_description', models.TextField(blank=True)),
                ('deck_restriction_ref', models.CharField(blank=True, max_length=100)),
                ('deck_restriction_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script_reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script_reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_value', models.BooleanField(default=False)),
                ('requires_target', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('event', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rank', models.IntegerField(default=0)),
                ('user_data', models.JSONField(default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CARD', 'Card'), ('EQUIP', 'Equipment'), ('CHARACTER', 'Character')], max_length=20)),
                ('pull_currency', models.CharField(choices=[('STANDARD_PULL', 'Standard Pull Currency'), ('LIMITED_PULL', 'Limited Pull Currency')], max_length=20)),
                ('is_limited', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hard_pity', models.IntegerField(default=80)),
                ('soft_pity_start', models.IntegerField(default=60)),
                ('featured_legendary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_legendary_in', to='core.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.character'),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('main_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks_main', to='core.character')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
                ('partner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_partner', to='core.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faction'),
        ),
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='core.subtype'),
        ),
        migrations.AddField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='core.subtype'),
        ),
        migrations.CreateModel(
            name='CardEffectBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('your_cards_in_hand', 'Your Cards In Hand'), ('enemy_cards_in_hand', 'Enemy Cards In Hand'), ('friendly_board_count', 'Friendly Board Count'), ('enemy_board_count', 'Enemy Board Count'), ('friendly_graveyard_count', 'Friendly Graveyard Count'), ('enemy_graveyard_count', 'Enemy Graveyard Count'), ('turn_number', 'Turn Number'), ('owner_health', 'Owner Health'), ('opponent_health', 'Opponent Health')], max_length=50, null=True)),
                ('targeting', models.CharField(blank=True, choices=[('ENEMY_BOARD', 'Enemy Board'), ('ENEMY_HERO', 'Enemy Hero'), ('ENEMY_BOARD_OR_HERO', 'Enemy Board Or Hero'), ('FRIENDLY_BOARD', 'Friendly Board'), ('FRIENDLY_HERO', 'Friendly Hero'), ('SELF', 'Self'), ('ANY', 'Any'), ('UNKNOWN', 'Unknown')], max_length=30, null=True)),
                ('zone', models.CharField(choices=[('BOARD', 'Board'), ('HAND', 'Hand'), ('DECK', 'Deck'), ('GRAVEYARD', 'Graveyard'), ('ANY', 'Any'), ('OATHZONE', 'Oathzone'), ('EXILE', 'Exile'), ('CONSUMABLE_BAG', 'Consumable Bag')], default='ANY', max_length=30)),
                ('scope', models.CharField(choices=[('SELF', 'Self'), ('OTHER_FRIENDLY', 'Other Friendly'), ('ANY_FRIENDLY', 'Any Friendly'), ('OTHER_ENEMY', 'Other Enemy'), ('ANY_OTHER', 'Any Other'), ('ANY', 'Any'), ('GLOBAL', 'Global')], default='SELF', max_length=30)),
                ('condition_value', models.IntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='core.card')),
                ('linked_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bindings', to='core.card')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.condition')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.effect')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('equipped', models.JSONField(default=dict)),
                ('consumables', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.banner')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
            options={
                'unique_together': {('banner', 'card')},
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PARTNER', 'Partner'), ('RIVAL', 'Rival'), ('FRIENDLY', 'Friendly'), ('LOVE', 'Love'), ('RESPECT', 'Respect')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_outgoing', to='core.character')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_incoming', to='core.character')),
            ],
            options={
                'unique_together': {('source', 'target', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='core.deck')),
            ],
            options={
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
