# Generated by Django 5.2.3 on 2025-07-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
