# Generated by Django 5.2.3 on 2025-08-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_auxiliarytype_card_auxilarytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='auxilarytype',
            new_name='auxiliarytype',
        ),
    ]
