# Generated by Django 5.2.3 on 2025-07-30 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trigger_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='validation_errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
