# Generated by Django 5.2.3 on 2025-07-31 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deck_validation_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='validation_errors',
        ),
        migrations.AddField(
            model_name='card',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.character'),
        ),
    ]
