# Generated by Django 5.2.3 on 2025-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_auxilarytype_card_auxiliarytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='auxiliarytype',
            field=models.CharField(choices=[('NONE', 'None'), ('REAGENT', 'Reagent'), ('OATH', 'Oath'), ('CONSUMABLE', 'Consumable'), ('FRAGMENT', 'Fragment'), ('RELIC', 'Relic'), ('TEMPLATE', 'Template')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, choices=[('SPELL', 'Spell'), ('UNIT', 'Unit'), ('EQUIPMENT', 'Equipment'), ('ASSET', 'Asset'), ('EVENT', 'Event'), ('TRAP', 'Trap'), ('RITUAL', 'Ritual'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
