# Generated by Django 5.2.3 on 2025-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_deck_validation_errors_card_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='auxilarytype',
            field=models.CharField(choices=[('NONE', 'None'), ('REAGENT', 'Reagent'), ('QUEST', 'Quest'), ('CONSUMABLE', 'Consumable'), ('FRAGMENT', 'Fragment')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='classlock',
            field=models.CharField(choices=[('SPECIALIST', 'Specialist'), ('SPELLWEAVER', 'Spellweaver'), ('BLOODBOUND', 'Bloodbound'), ('SHADE', 'Shade'), ('MACHINIST', 'Machinist'), ('SOULFORGED', 'Soulforged'), ('GAMBLER', 'Gambler'), ('OATHBOUND', 'Oathbound'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
