# Generated by Django 5.2.3 on 2025-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_card_auxiliarytype_alter_card_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffectbinding',
            name='targeting_rule',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AOE', 'Aoe'), ('RANDOM', 'Random'), ('WEAKEST', 'Weakest'), ('STRONGEST', 'Strongest'), ('NONE', 'None')], max_length=30, null=True),
        ),
    ]
