# Generated by Django 5.2.3 on 2025-08-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_auxilarytype_card_classlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_data',
            field=models.JSONField(default=dict),
        ),
    ]
