# Generated by Django 5.2.3 on 2025-08-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cardeffectbinding_targeting_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordEffectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('your_cards_in_hand', 'Your Cards In Hand'), ('enemy_cards_in_hand', 'Enemy Cards In Hand'), ('friendly_board_count', 'Friendly Board Count'), ('enemy_board_count', 'Enemy Board Count'), ('friendly_graveyard_count', 'Friendly Graveyard Count'), ('enemy_graveyard_count', 'Enemy Graveyard Count'), ('turn_number', 'Turn Number'), ('owner_health', 'Owner Health'), ('opponent_health', 'Opponent Health')], max_length=50, null=True)),
                ('targeting', models.CharField(blank=True, choices=[('ENEMY_BOARD', 'Enemy Board'), ('ENEMY_HERO', 'Enemy Hero'), ('ENEMY_BOARD_OR_HERO', 'Enemy Board Or Hero'), ('FRIENDLY_BOARD', 'Friendly Board'), ('FRIENDLY_HERO', 'Friendly Hero'), ('SELF', 'Self'), ('ANY', 'Any'), ('UNKNOWN', 'Unknown')], max_length=30, null=True)),
                ('targeting_rule', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AOE', 'Aoe'), ('RANDOM', 'Random'), ('WEAKEST', 'Weakest'), ('STRONGEST', 'Strongest'), ('NONE', 'None')], max_length=30, null=True)),
                ('condition_value', models.IntegerField(blank=True, null=True)),
                ('zone', models.CharField(choices=[('BOARD', 'Board'), ('HAND', 'Hand'), ('DECK', 'Deck'), ('GRAVEYARD', 'Graveyard'), ('ANY', 'Any'), ('OATHZONE', 'Oathzone'), ('EXILE', 'Exile'), ('CONSUMABLE_BAG', 'Consumable Bag')], default='ANY', max_length=30)),
                ('scope', models.CharField(choices=[('SELF', 'Self'), ('OTHER_FRIENDLY', 'Other Friendly'), ('ANY_FRIENDLY', 'Any Friendly'), ('OTHER_ENEMY', 'Other Enemy'), ('ANY_OTHER', 'Any Other'), ('ANY', 'Any'), ('GLOBAL', 'Global')], default='SELF', max_length=30)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.condition')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.effect')),
                ('linked_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_linked_bindings', to='core.card')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trigger')),
            ],
        ),
    ]
