# Generated by Django 5.2.3 on 2025-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_keywordeffecttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text="Selecting a keyword will copy its bindings into this card's bindings on save.", related_name='cards_using_keyword', to='core.keywordeffecttemplate'),
        ),
    ]
