# Generated by Django 5.2.3 on 2025-08-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_card_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffectbinding',
            name='keyword_template',
            field=models.ForeignKey(blank=True, help_text='Optional: pick a keyword to auto-fill binding fields', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.keywordeffecttemplate'),
        ),
    ]
