# Generated by Django 5.2.3 on 2025-08-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_deck_owner_usercharacterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CARD', 'Card'), ('EQUIP', 'Equipment'), ('CHARACTER', 'Character')], max_length=20)),
                ('pull_currency', models.CharField(choices=[('STANDARD_PULL', 'Standard Pull Currency'), ('LIMITED_PULL', 'Limited Pull Currency')], max_length=20)),
                ('is_standard', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hard_pity', models.IntegerField(default=80)),
                ('soft_pity_start', models.IntegerField(default=60)),
                ('featured_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_banners', to='core.card')),
            ],
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_modifier', models.FloatField(default=1.0)),
                ('is_featured', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.banner')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
        ),
    ]
