# Generated by Django 5.2.3 on 2025-08-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_card_image_path_banner_banneritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='featured_card',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_standard',
        ),
        migrations.RemoveField(
            model_name='banneritem',
            name='rate_modifier',
        ),
        migrations.AddField(
            model_name='banner',
            name='featured_legendary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_legendary_in', to='core.card'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_limited',
            field=models.BooleanField(default=True),
        ),
    ]
