# Generated by Django 5.2.3 on 2025-08-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cardeffectbinding_keyword_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='keywords',
        ),
    ]
