# Generated by Django 5.2.3 on 2025-08-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_banner_featured_card_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banneritem',
            unique_together={('banner', 'card')},
        ),
    ]
