# Generated by Django 5.2.3 on 2025-08-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_banneritem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffectbinding',
            name='condition_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardeffectbinding',
            name='linked_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bindings', to='core.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='auxilarytype',
            field=models.CharField(choices=[('NONE', 'None'), ('REAGENT', 'Reagent'), ('OATH', 'Oath'), ('CONSUMABLE', 'Consumable'), ('FRAGMENT', 'Fragment'), ('RELIC', 'Relic')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardeffectbinding',
            name='scope',
            field=models.CharField(choices=[('SELF', 'Self'), ('OTHER_FRIENDLY', 'Other Friendly'), ('ANY_FRIENDLY', 'Any Friendly'), ('OTHER_ENEMY', 'Other Enemy'), ('ANY_OTHER', 'Any Other'), ('ANY', 'Any'), ('GLOBAL', 'Global')], default='SELF', max_length=30),
        ),
    ]
