# Generated by Django 5.2.3 on 2025-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cardeffectbinding_condition_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffectbinding',
            name='zone',
            field=models.CharField(choices=[('BOARD', 'Board'), ('HAND', 'Hand'), ('DECK', 'Deck'), ('GRAVEYARD', 'Graveyard'), ('ANY', 'Any'), ('OATHZONE', 'Oath Zone'), ('EXILE', 'Exile'), ('CONSUMABLE_BAG', 'Consumable Bag')], default='ANY', max_length=30),
        ),
    ]
