# Generated by Django 5.2.3 on 2025-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cardeffectbinding_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffectbinding',
            name='zone',
            field=models.CharField(choices=[('BOARD', 'Board'), ('HAND', 'Hand'), ('DECK', 'Deck'), ('GRAVEYARD', 'Graveyard'), ('ANY', 'Any'), ('OATHZONE', 'Oathzone'), ('EXILE', 'Exile'), ('CONSUMABLE_BAG', 'Consumable Bag')], default='ANY', max_length=30),
        ),
    ]
